const values = [
  'Affix',
  'Button',
  'Alert',
  'Anchor',
  'Space',
  'Divider',
  'SpaceCompact',
  'SpaceAddon',
  'StyleProvider',
  'Flex',
  'ConfigProvider',
  'Col',
  'Row',
  'Badge',
  'BadgeRibbon',
  'BorderBeam',
  'Tag',
  'CheckableTag',
  'CheckableTagGroup',
  'Layout',
  'LayoutHeader',
  'LayoutFooter',
  'LayoutContent',
  'LayoutSider',
  'Empty',
  'Result',
  'Spin',
  'Skeleton',
  'SkeletonButton',
  'SkeletonAvatar',
  'SkeletonInput',
  'SkeletonImage',
  'SkeletonNode',
  'Statistic',
  'StatisticTimer',
  'Descriptions',
  'DescriptionsItem',
  'Timeline',
  'TimelineItem',
  'Watermark',
  'QRCode',
  'Collapse',
  'CollapsePanel',
  'Tooltip',
  'Segmented',
  'Popover',
  'Popconfirm',
  'FloatButton',
  'BackTop',
  'FloatButtonGroup',
  'Menu',
  'SubMenu',
  'MenuItem',
  'MenuItemGroup',
  'MenuDivider',
  'Dropdown',
  'Tour',
  'Breadcrumb',
  'BreadcrumbItem',
  'BreadcrumbSeparator',
  'Avatar',
  'AvatarGroup',
  'Form',
  'FormItem',
  'Checkbox',
  'CheckboxGroup',
  'Radio',
  'RadioGroup',
  'RadioButton',
  'Switch',
  'ColorPicker',
  'Slider',
  'Input',
  'InputSearch',
  'InputPassword',
  'InputOTP',
  'InputGroup',
  'InputNumber',
  'TextArea',
  'Typography',
  'TypographyText',
  'TypographyTitle',
  'TypographyParagraph',
  'TypographyLink',
  'Tabs',
  'TabPane',
  'Select',
  'SelectOption',
  'SelectOptGroup',
  'Splitter',
  'SplitterPanel',
  'Card',
  'CardGrid',
  'CardMeta',
  'Masonry',
  'Rate',
  'Progress',
  'Drawer',
  'Modal',
  'Steps',
  'Image',
  'ImagePreviewGroup',
  'App',
  'Tree',
  'DirectoryTree',
  'TreeSelect',
  'Upload',
  'UploadDragger',
  'Pagination',
  'Transfer',
  'Mentions',
  'Carousel',
  'Cascader',
  'Table',
  'TableColumn',
  'TableSummary',
  'TableSummaryRow',
  'TableSummaryCell',
  'Calendar',
  'DatePicker',
  'DateRangePicker',
  'TimePicker',
  'TimeRangePicker',
  'AutoComplete',
  'AutoCompleteOption',
] as const

export type ComponentName = (typeof values)[number]

const componentRegistrationAliases: Partial<Record<ComponentName, string>> = {
  BackTop: 'FloatBackTop',
  DateRangePicker: 'RangePicker',
  InputOTP: 'InputOtp',
  QRCode: 'Qrcode',
  TextArea: 'Textarea',
}

export const componentParentDependencies: Partial<Record<ComponentName, ComponentName>> = {
  BreadcrumbItem: 'Breadcrumb',
  BreadcrumbSeparator: 'Breadcrumb',
  CollapsePanel: 'Collapse',
  DescriptionsItem: 'Descriptions',
  MenuDivider: 'Menu',
  MenuItem: 'Menu',
  MenuItemGroup: 'Menu',
  SubMenu: 'Menu',
  TabPane: 'Tabs',
  TableColumn: 'Table',
  TableSummary: 'Table',
  TableSummaryCell: 'Table',
  TableSummaryRow: 'Table',
  TimelineItem: 'Timeline',
}

export function resolveComponentRegistrationName(component: ComponentName) {
  return componentRegistrationAliases[component] ?? component
}

export default values
